# Site
name: "hojimat.com"
title: "Ravshan Hojimatov"
description: "Personal website of an economist Ravshan Hojimatov (Ravshanbek Khodzhimatov)"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'https://hojimat.com'
baseurl: ''
include: ["_pages"]
permalink: /:title/
email: ravshan.academic@gmail.com

# Authors
authors:
  rsk:
    name: Ravshan
    display_name: Ravshan
    avatar: 'assets/images/avatar.jpg'
    email: ravshan.academic@gmail.com
    twitter: https://twitter.com/hojimatx
    description: "Economist modeling social phenomena as complex systems."

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-spaceship
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"
#

sass:
  load_paths:
    - _sass

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
